{
 "title": "Nginx访问日志 历史数据 仪表板",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# <center>Nginx 访问日志数据可视化 </center>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  last_login AS \"time\",\n  id\nFROM auth_user\nWHERE\n  $__timeFilter(last_login)\nORDER BY last_login"
    }
   ]
  },
  {
   "title": "请求方法占比",
   "type": "bargauge",
   "description": "柱状图",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tNOW() as time,\r\n\thttp_method as metric,\r\n\tcount as value\r\nFROM method"
    }
   ]
  },
  {
   "title": "http的访问量",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count\r\nFROM https\r\nwhere scheme='http'"
    }
   ]
  },
  {
   "title": "https的访问量",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count\r\nFROM https\r\nwhere scheme='https'"
    }
   ]
  },
  {
   "title": "请求状态占比",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tNOW() as time,\r\n\tCONCAT(status,'') as metric,\r\n\tcount as value\r\nFROM status"
    }
   ]
  },
  {
   "title": "日志流数据",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ip as 'IP地址',\r\n  user as '用户',\r\n  time as '时间',\r\n  http_method as '请求方式',\r\n  http_path as '请求路径'\r\nFROM df"
    }
   ]
  }
 ]
}