{
 "title": "Nginx访问日志 历史数据 仪表板",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "网站中的小文件与大文件识别，将占用带宽资源大的文件分离？",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "#8 网页URL层数与性能的关系？",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "URL层数",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  http_path AS 请求路径,\r\n  http_path_depth AS 深度\r\nFROM grafana_top_depth\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
     "options": {
      "content": "# <center>Nginx 访问日志数据可视化 </center>"
     },
     "targets": [
      {
       "rawSql": "SELECT\n  last_login AS \"time\",\n  id\nFROM auth_user\nWHERE\n  $__timeFilter(last_login)\nORDER BY last_login"
      }
     ]
    },
    {
     "title": "日志流数据",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  ip as 'IP地址',\r\n  user as '用户',\r\n  FROM_UNIXTIME(time/1000) as '时间',\r\n  http_method as '请求方法',\r\n  http_path as '请求路径',\r\n\thttp_version as 'HTTP协议版本',\r\n\tstatus as 'HTTP响应状态码',\r\n\tbytes as '传送字节数',\r\n\thttp_content_type,\r\n\treferer as '来源',\r\n\tos as '操作系统',\r\n\tscheme\r\nFROM df"
      }
     ]
    },
    {
     "title": "请求方法占比",
     "type": "bargauge",
     "description": "柱状图",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n\tNOW() as time,\r\n\thttp_method as metric,\r\n\tcount as value\r\nFROM method"
      }
     ]
    },
    {
     "title": "来源操作系统",
     "type": "piechart",
     "description": "饼图",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  time AS \"time\",\n  metric,value\nFROM grafana_os\nORDER BY time"
      }
     ]
    },
    {
     "title": "http的访问量",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  *\r\nFROM grafana_https\r\nwhere metric='http'"
      }
     ]
    },
    {
     "title": "https的访问量",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  *\r\nFROM grafana_https\r\nwhere metric='https'"
      }
     ]
    }
   ]
  },
  {
   "title": "#3 检查被访问的资源名称，分析出网站的具体哪个内容最受欢迎",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "访问量前十页面",
     "type": "table",
     "description": "（高频点击，访问量前10页面）检查被访问的资源名称，分析出网站的具体哪个内容最受欢迎——table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\r\n  http_path AS 请求路径,\r\n  referer AS 来源,\r\n  count AS 请求次数\r\nFROM grafana_top_url\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "#4 检查用户访问的返回代码，分析出网站是否存在错误。",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "异常页面记录",
     "type": "table",
     "description": "（异常页面记录） 检查用户访问的返回代码，分析出网站是否存在错误——table （错误>500）",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n  http_method AS 请求方法,\n  http_path AS 请求路径,\n  status AS HTTP响应状态码,\n  count AS 请求次数\nFROM grafana_df_err\norder by count desc"
      }
     ]
    },
    {
     "title": "请求状态占比",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n\tNOW() as time,\r\n\tCONCAT(status,'') as metric,\r\n\tcount as value\r\nFROM status"
      }
     ]
    }
   ]
  }
 ]
}